[project]
name = "LoadingPrograms"
version = "0.1.0"
description = "Testing program loading using dependencies"
authors = [
    {name = "gamercha", email = "gamercha@student.42madrid.com"}
]

requires-python = ">=3.12.3"
dependencies = [
"matplotlib==3.11.1", "numpy==2.5.2",
"pandas==3.0.5", "requests==2.34.2"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false